name: 🐛 Bug Report
description: Report a bug or issue with CCDebugger
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        When I try to...
        I expected... but instead...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open Claude Code
        2. Type /ccdebug...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: CCDebugger should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, CCDebugger...
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: CCDebugger Version
      options:
        - Latest
        - 0.1.0
        - 0.0.9
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      placeholder: e.g., 1.85.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu)
        - Linux (Other)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      render: shell
      placeholder: |
        Error messages from VS Code Output panel or console...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem (screenshots, code samples, etc.)
    validations:
      required: false