name: 💡 Feature Request
description: Suggest a new feature or enhancement for CCDebugger
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for CCDebugger! Your ideas help make debugging better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why do you need it?
      placeholder: |
        I often encounter situations where...
        It would be helpful if CCDebugger could...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this feature implemented?
      placeholder: |
        I envision this working by...
        The feature could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Currently, I work around this by...
        I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: categories
    attributes:
      label: Feature Categories
      description: Which areas does this feature relate to?
      options:
        - label: AI Analysis
        - label: Command Completion
        - label: VS Code Extension
        - label: Performance
        - label: User Interface
        - label: Templates
        - label: Multi-language Support
        - label: Integration
        - label: Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        Screenshots, code examples, or links to similar features...
    validations:
      required: false